### ISSUE TITLE
Data not showing up

### ISSUE THREAD

**Issue by KaitoCross** [Dom1n1c/MMM-EFA-departures#13]
Hey :) I'd love to use your departures module to display the departures of Boisheim Bahnhof (Verkehrsverbund Rhein-Ruhr). I've configured the script like in the example, but no departures show up at all, even after restarting MagicMirror. It just says loading for hours. The module is loaded though and displayed.

**Comment by Dom1n1c** [comment]
Should work again, please do a git pull.

**Comment by KaitoCross** [comment]
Works fine now, thank you! :)
