### ISSUE TITLE
Add realtime data, if available (show delay)

### ISSUE THREAD

**Issue by Dom1n1c** [Dom1n1c/MMM-EFA-departures#2]

**Comment by luckylulatsch** [comment]
vielleicht hilft dir die Dokumentation weiter ...[](http://data.linz.gv.at/katalog/linz_ag/linz_ag_linien/fahrplan/LINZ_AG_Linien_Schnitstelle_EFA_v7_Echtzeit.pdf)

würde mich für Tests im VVS-Gebiet anbieten, aber müsste ja theoretisch in allen Gebieten funktionieren, falls es läuft ;)

**Comment by Dom1n1c** [comment]
Hey :)

Ich würde gerne folgende Dinge einbauen, switchen zwischen absoluter und relativer Zeit (ohne aktivieren von toggleDepTime sowie die realtime-Abfahrt. Zwei variablen, in etwa:
```
useRealtime: false,
relativeDepTime: true,
```

könnte man dazu nutzen.
die DateTime variable muss dann aber RealDateTime heißen

```
 var departureTimeReal = new Date(data.realDateTime.year, data.realDateTime.month - 1, data.realDateTime.day, data.realDateTime.hour, data.realDateTime.minute, 0);
        var departure = document.createElement("td");
        departure.className = "departures__departure";
        departure.innerHTML = '<span class="departures__departure__time-relative small bright">' + moment(departureTimeReal).fromNow() + '</span><span class="departures__departure__time-clock small bright">' + moment(departureTimeReal).format('HH:mm') + '</span>';

Habe die informationen aus einem anderen Projekt:
https://github.com/opendata-stuttgart/metaEFA/blob/master/meta_efa/main/utils.py#L67

Vielleicht kann mir jemand dabei helfen, die Echtzeitdaten einzupflegen.
```

**Comment by Dom1n1c** [comment]
das heißt in dem node_helper muss die URL angepasst werden, um realtime Daten zu bekommen, (&useRealtime=1) danach gibt es die realdatetime variablen erst in der ausgabe.

**Comment by luckylulatsch** [comment]
hey,

tut mir leid wenn ich dich vertrösten muss, bis jetzt habe ich noch kaum Ahnung von Web Programmierung , bin aber zur Zeit dabei dein bisheriges Modul zu verstehen.

Mit dem (&userealtime=1) hast du aber Recht. Man bekommt dann noch ein JSON-Objekt "mehr" zurück mit den Echtzeitdaten.

BTW in Stuttgart gibt es zur Zeit neue Entwicklungen bei der EFA [](https://www3.vvs.de/mng/#/XSLT_TRIP_REQUEST2@init) mit einer zweiten Version die mit deeplinks? arbeitet...

**Comment by Dom1n1c** [comment]
Ich versuche die Features in den unterschiedlichen Skripts in den nächsten Tagen einzubinden. 

Schau mal in den Log von PM2, dann siehst du die ganze URL und kannst die Daten prüfen, für Chrome gibt's diverse addons für JSON Daten/ RESTful APIs

**Comment by luckylulatsch** [comment]
alles klar cool. Ja ich bin noch dabei das alles zu verstehen, deshalb bin ich wohl noch nicht ganz hilfreich ;)

**Comment by luckylulatsch** [comment]
also hab jetzt ungefähr verstanden wies geht :) 

wäre es aber nicht geschickter statt die DateTime durch RealDateTime zu ersetzen einfach eine weitere Spalte anzufügen in der dann entweder die RealDateTime steht oder "+X"-Label ? 

Man müsste also das in getDom und in die efa_url einpflegen?

**Comment by Dom1n1c** [comment]
Habs es nun eingepflegt.
wenn aktiviert, wird realdeptime bezogen.
