### ISSUE TITLE
show delay next to scheduled departure (for instance 20:05+10)

### ISSUE THREAD

**Issue by Dom1n1c** [Dom1n1c/MMM-EFA-departures#5]

**Comment by luckylulatsch** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/27732414/25784038/ee259a56-3366-11e7-9dc8-5ac3d31e8e72.PNG)

hab bei mir sowas hinzugefügt :)

**Comment by Dom1n1c** [comment]
Kannst du mir sagen, welche Anpassungen du vorgenommen hast?
Waren bei dir die Zielhaltestellen (Leinfelden usw.) schon so kurz, oder hast du Sie anpassen müssen?

**Comment by luckylulatsch** [comment]
Ich hab nur 2 neuen CSS-Klassen hinzugefügt , die createRow-Funktion bissle geändert und die absoluten Abfahrtszeiten dauerhaft eingestellt , fand ich geschickter :) 

Und ne , die Zielhaltestellen sind schon so kurz. Ist ganz praktisch in Stuttgart :) 


Grüße

**Comment by Magic-Pi** [comment]
Wow...sieht sehr schön aus. Könntest du die Klassen hier posten? Bin nicht so der CSS Typ ;)

**Comment by Trekky12** [comment]
I think that issue can be closed now

**Comment by Dom1n1c** [comment]
As added with [PR #11](https://github.com/Dom1n1c/MMM-EFA-departures/pull/11), the issue is resolved now.
