### ISSUE TITLE
Station and Line IDs

### ISSUE THREAD

**Issue by Dom1n1c** [Dom1n1c/MMM-EFA-departures#6]
Using a little script, i extracted a few stations.
Most of them are from the vrr region.
[stations.txt](https://github.com/Dom1n1c/MMM-EFA-departures/files/999639/stations.txt)
Same for the lines
[lines.txt](https://github.com/Dom1n1c/MMM-EFA-departures/files/999640/lines.txt)

**Comment by Magic-Pi** [comment]
Can you post the script or can you run the script for the RVF region? If you need any further information - please let me know.
