### ISSUE TITLE
Option to Filter possible?

### ISSUE THREAD

**Issue by Cadi0815** [Dom1n1c/MMM-EFA-departures#7]
Hi Dom1n1k,
Thank you very much for this great Module. I was able to configure it for GVH requests (Hannover). Is it possible to filter IDs because i need the informations only for 3 lines but i get 6 different lines.

Best
Cadi

**Comment by Dom1n1c** [comment]
Yeah, of course you can filter lines,

instead of:

`lines: ['all'],`

you should enter the desired lines like:

`lines: ['DDB:92E01: :H','DDB:92E01: :R'],`

but you should first get the Line IDs using chrome developer tools or some other data source.
So in your case the brackets should contain 3 values.

Btw: would you please tell me the API Endpoint, so that i can add it to the Readme.

**Comment by Cadi0815** [comment]
Hi Dom1n1c,


thanks for your quick response!
I will try to find out as you described.
The API endpoint of GVH Hannover is http://mobile.efa.de/mobile3/XSLT_DM_REQEST


Cheers
Cadi



-----Ursprüngliche Mitteilung----- 
Von: Dominic Spatz <notifications@github.com>
An: Dom1n1c/MMM-EFA-departures <MMM-EFA-departures@noreply.github.com>
Cc: Cadi0815 <ilkakc@aol.com>; Author <author@noreply.github.com>
Verschickt: Do, 7. Sept 2017 21:24
Betreff: Re: [Dom1n1c/MMM-EFA-departures] Option to Filter possible? (#7)



Yeah, of course you can filter lines,
instead of:
lines: ['all'],
you should enter the desired lines like:
lines: ['DDB:92E01: :H','DDB:92E01: :R'],
but you should first get the Line IDs using chrome developer tools or some other data source.
So in your case the brackets should contain 3 values.
Btw: would you please tell me the API Endpoint, so that i can add it to the Readme.

**Comment by Cadi0815** [comment]
Hi Dom1n1k,

here is the API endpoint of GVH: `http://mobil.efa.de/mobile3/XSLT_DM_REQUEST?`

I am not able to filter the lines because the data is not coded like in your example, but I see the line names as plaintext.
I´m a really n00b in debugging. Can you please assist? I started the debugging tools with F12 and I have found data in Sources tab. But the data there is plaintext.

Best
Cadi

**Comment by Dom1n1c** [comment]
Well, mobil.efa.de does not seem to be a provider(gvh), its a page hosted by Mentz DV/with a newer version of the API.

i can only find some Stations operated by the German Railway:
```
Leinhausen
Hannover Anderten-Misburg
Bismarckstraße
Bornum
Kleefeld
Linden/Fischerhof
Hannover-Vinnhorst
Karl-Wiechert-Allee
Bahnhof Nordstadt
Ledeburg
Hannover Flughafen
Flughafen Bf
Hbf ZOB
Hannover-Wülfel
```
(I used the vrr page, which will fit like the neutral page.)


Using chrome, i entered this / used the show-source shortcut:
`view-source:http://efa.vrr.de/standard/XSLT_DM_REQUEST`

you have to select a Station, and then you can get the Line IDs

This is the output, when i selected one of those stations and added all lines to the departure monitor.

` document.location.href="XSLT_DM_REQUEST?language=de&itdLPxx_dmRefresh=&typeInfo_dm=stopID&nameInfo_dm=80002225&useRealtime=1&mode=direct&line=DDB:92H01: :H&line=DDB:92H01: :R&line=DDB:92H02: :H&line=DDB:92H02: :R&line=DDB:92H05:P:H&line=DDB:92H05:P:R&line=DDB:92H51: :H";`
