### ISSUE TITLE
efa url for Freiburg, Germany

### ISSUE THREAD

**Issue by Magic-Pi** [Dom1n1c/MMM-EFA-departures#9]
Hi guys, 

I'm looking for an efa departures for Freiburg, south Germany. I found this website for a request. I think this is the right one:
http://www.efa-bw.de/nvbw/XSLT_DM_REQUEST?language=de&itdLPxx_frames=&itdLPxx_origin=

Or is this the rightefa url?:
http://www.efamobil.de/mobile3/XSLT_DM_REQUEST

Sorry....I'm a newby ;)

My questions are:
1.  I need two limits for the script (http://www.eg-blog.de/?p=822). Where can I find these limits? Or is it just try and error? ;)
2.  Is the rest of the parameters for the config.js file the same? 

Thanks in advance

**Comment by Dom1n1c** [comment]
Search for the name_dm parameter
Example: https://www.efa-bw.de/nvbw/XSLT_DM_REQUEST?language=de&dmMacro=nvbwLink&name_dm=5200026&type_dm=any

Is Heilbronn Hbf. 

Click on 'ihr link' and you'll see the name_dm and line parameter.
